import = [ "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]
live_config_reload = true
[shell]
program = "/usr/bin/tmux"
args = ["-u"] 
[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 5
y = 10

[font]
size = 10.0
#
[font.bold]
family = "MesloLGS NF"
style = "Heavy"

[font.bold_italic]
family = "MesloLGS NF"
style = "Heavy Italic"

[font.italic]
family = "MesloLGS NF"
style = "Medium Italic"

[font.normal]
family = "MesloLGS NF"
style = "Medium"
